### ISSUE TITLE
Design doc review #1 - MVP list and Schema

### ISSUE THREAD

**Issue by aracpyon** [henryzihaohuang/GreenMile#1]
**MVP**

- [x] Add dates on each MVP!
- [x] (User auth) User will see the error messages when signup/login fails
- [x] Follow the MVP list order given by aA: 
          Dashboard + Portfolio
          Asset/Stock Detail
          Watchlist
          Asset/Stock Search 
`Watchlist` should come after `Asset/Stock Detail`. And `Asset/Stock Search` is the last. Update your entire MVPs based on this order change. 
- [x] (Dashboard & Portfolio) Since users cannot invest real money to your app. Every user will start with $10,000 to invest. 
- [x] (Dashboard & Portfolio) You will need external api for the stock data. I recommend [IEXCloud](https://iexcloud.io/). This will take time so start reading/getting familiar with its docs as soon as possible. 

**Schema**
- [x] (portfolio) change `shares` to `num_shares` to be more semantic
- [x] (portfolio) remove `company_name` and `abbreviation`. Add `stock_id`. 
- [x] (watchlist) If users can make many `watchlists`, you need a joins table between `watchlists` and `stocks`. Remove `company_name` and `abbreviation` and create a joins table that has `stock_id` and `watch_list_id`. This way watchlist and have many stocks and stocks can have many watchlists. (many to many relationship)
- [x] (purchase_order) Is this table for sell/buy history for the currentUser for each stock? If so, remove `company_name` and `abbreviation` and add `stock_id`. 
- [x] (purchase_order) Instead `sell_price` and `buy_price` columns, make `transaction_type` (sell or buy) and `price` columns.

**Comment by henryzihaohuang** [comment]
Hi Ara! 

Thanks for the detailed feedback! I appreciate you taking the time. I've gone through every item and reviewed how I could make changes. 

I do have a question about the portfolio tables. I was not sure if you wanted me to make a joins table for the user portfolio and stocks as well? Please let me know. I left a note with more details in the schema page.

Please let me know if you see any other issues. Thank you! My frontend routes have been updated as well.

**Comment by aracpyon** [comment]
Great job! I just posted another review on Frontend Routes. Please check it out and let me know if you have questions. 

No, you don't need the joins table between portfolio and stocks because portfolio itself is working like a joins table between the user and stocks.

**Comment by aracpyon** [comment]
- [ ] Actually, let's remove balance from Users. Since you have the transaction history and all the users start with $10,000, you technically can calculate the balance with simple calculations. If we have this balance column in database, you have to send an ajax request to the backend everytime there is a chance and this could be a hassle.

**Comment by henryzihaohuang** [comment]
Ah ok. That makes sense. I'll also make a note of it in the MVP to reflect the balance calculations.
