### ISSUE TITLE
Design doc review #2 - sample state

### ISSUE THREAD

**Issue by aracpyon** [henryzihaohuang/GreenMile#2]
**Sample State**
- [x] Update your sample states based on the changes on Schema.

**Comment by henryzihaohuang** [comment]
This has been updated. The following looks so strange, but for the sake of normalization and keeping things un-nested, is it okay?: 
``` js
portfolio: {
            1: {
                id: 1,
                user_id: 7,
                stock_id: 5,
                num_shares: "400"
            },

            1: {
                id: 1,
                user_id: 7,
                stock_id: 4,
                num_shares: "888"
            }
        },
```

**Comment by aracpyon** [comment]
Henry, yes, portfolio looks good to me! Here are extra stuff you need to update:
- [ ] Since it's js, make everything camelCased. 
- [ ] remove `balance` from the currentUser. 
- [ ] You don't have to make a slice of `watchlisted_stocks`. Instead, add a slice of `watchedStockIds` to `watchlist` such as:
```js
watchlist: {
            1: {
                id: 1,
                name: "Goods and Services",
                userId: 7,
                watchedStockIds: [1, 5]
               },
            2: {
                id: 1,
                name: "Technology",
                userId: 7,
                watchedStockIds: [2, 3, 4, 7]
            }
        },
```

**Comment by henryzihaohuang** [comment]
Ah of course! Sorry about that, haha. Old ruby habits die hard. Updated!

**Comment by aracpyon** [comment]
Awesome!
