### ISSUE TITLE
Design doc review #3 - Backend and Frontend Routes

### ISSUE THREAD

**Issue by aracpyon** [henryzihaohuang/GreenMile#3]
**Backend Routes**
- [x] (users) `GET /api/users/:id` You don't need to build this until you are really working on the user's profile. 
- [x] (portfolio) Don't make your portfolio nested to users because you are only going to show the currentUser's portfolio. 
- [x] (watchlist) You don't have to nest watchlists to users for the same reason above. 

**Frontend routes**
- [x] Indent `<Component />` aligned with `NavBar`
- [x] sidebars (`watchlists` and `buy/sell`) are part of components
- [x] `/users/:userId` you don't need this route. 
- [x] `/users/:userId/portfolio` => change this to `/portfolio`. Porfolio is going to show only the currentUser's information. 
- [x] `/stocks/:stockId` Add `buy/sell` component here.

**Comment by henryzihaohuang** [comment]
All updated. Please let me know if there are any other issues! Thank you Ara.

**Comment by aracpyon** [comment]
**Backend**
- [ ] `GET /api/portfolio` => Probably you need to make it as a show page so it will be `GET /api/portfolio/:id`
- [ ] `GET /api/watchlist` => this is correct but I just wanted to mention this; this route will bring all the watchlists that belong to the currentUser. 
- [ ] You still need to make `<Component />`aligned with NavBar for example...

- /
     - Root
     - App
          - NavBar
                - searchBar
                - portfolio(button or link)
                - account(button or link)
                - Login / Sign up(buttons or link)
                - Logout
         - <Component />s => details shown below
         - Footer

**Comment by henryzihaohuang** [comment]
Awesome, thank you for bringing those notes to my attention. I'll keep them in mind now. 

Sorry for the misunderstanding on the frontend route edits, I've updated them now~!

**Comment by aracpyon** [comment]
Awesome! Although you don't need to metion `sidebar`, `watchlist` under the `<component />s` because the details are shown below, but it's okay. Great job!
